name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - run: npm test
      - run: node ./scripts/set_version.js "0.0.1-alpha-$(git rev-parse --short "$GITHUB_SHA")"
        env:
          BUILD_ENV: CI
      - run: node ./scripts/publish_builds.js
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
